---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: <nat_ip>
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: <nat_ip>
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible      

vector:
  hosts:
    vector-01:
      ansible_host: <nat_ip>
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible