---
all:
  hosts:
    nexus-01:
      ansible_host: 51.250.85.240
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible
  children:
    nexus:
      hosts:
        nexus-01: