---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 84.201.130.52
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible

vector:
  hosts:
    vector-01:
      ansible_host: 89.169.151.71
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible