---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 89.169.133.240
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 62.84.114.220
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible      

vector:
  hosts:
    vector-01:
      ansible_host: 89.169.153.181
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible