---
- name: Vector block
  block:
    - name: Add the Vector repo
      ansible.builtin.shell: bash -c "$(curl -L https://setup.vector.dev)"
      register: vector_repo
      changed_when: vector_repo.stdout.find('/etc/yum.repos.d/vector.repo') != -1

    - name: Install vector packages
      become: true
      ansible.builtin.yum:
        name:
          - vector

    - name: Add config
      become: true
      ansible.builtin.template:
        src: templates/vector.j2
        dest: /etc/vector/vector.yaml
        mode: "0755"
      notify: Start vector service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
