apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-dep
  labels:
    app: vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vol
  template:
    metadata:
      labels:
        app: vol
    spec:
      containers:
      - name: test
        image: busybox
        resources: { limits: { cpu: "1", memory: "100Mi"  } }
        volumeMounts:
          - mountPath: /logs
            name: vol1
        command: ["sh", "-c", 'while true; do echo "$(date) - Log entry" >> /logs/time.txt; sleep 5; done']

      - name: multitool
        image: wbitt/network-multitool
        resources: { limits: { cpu: "1", memory: "100Mi"  } }
        volumeMounts:
        - mountPath: /logs
          name: vol1
        env:
        - name: HTTP_PORT
          value: "80"
        - name: HTTPS_PORT
          value: "443"
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 443
          name: https-port
      restartPolicy: Always
      volumes:
      - name: vol1
        hostPath:
          path: /var/kube/test
          type: DirectoryOrCreate
