apiVersion: v1
kind: ConfigMap
metadata:
  name: web-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Test Web Page</title>
    </head>
    <body>
        <h1>Hello from Test Page!</h1>
        <p>This page is served from a ConfigMap via Nginx.</p>
    </body>
    </html>