---
all:
  hosts:
    sonar-01:
      ansible_host: 89.169.143.222
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible
    nexus-01:
      ansible_host: 130.193.39.119
      ansible_connection: ssh
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/yc-ansible
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: <someuser>