{
 "title": "Neto",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Free Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"node_exporter_metrics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 1min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_load1{job=\"node_exporter_metrics\", instance=\"192.168.0.184:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "node_load5{job=\"node_exporter_metrics\", instance=\"192.168.0.184:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{job=\"node_exporter_metrics\", mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPULA 15min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "node_load15{job=\"node_exporter_metrics\", instance=\"192.168.0.184:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}