services:
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    container_name: grafana
  
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    container_name: prometheus
    volumes:
      - '/home/atimofeev/Scripts/prometheus.yml:/etc/prometheus/prometheus.yml'

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'