pipeline {
    agent {
  label 'ansible'
    }
    stages {
        stage ('Git'){
            steps {
                git branch: 'Jenkins', credentialsId: '1194e273-c14c-4c3d-be72-e59a48985370', url: 'git@github.com:alextee-dev/vector-role.git'
            }
        }
        stage ('Molecule'){
                steps {
                sh 'molecule test'
            }
        }
        
    }
}