apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name.svc2 }}
spec:
  selector:
    app: {{ .Values.name.web2 }}
  ports:
  - name: multitool
    protocol: TCP
    port: 1180
    targetPort: 1180