apiVersion: v1
kind: Service
metadata:
  name: web-ext
spec:
  selector:
    app: web
  ports:
  - name: nginx
    protocol: TCP
    port: 9003
    targetPort: 80
    nodePort: 30000
  - name: multitool
    protocol: TCP
    port: 9004
    targetPort: 8080
    nodePort: 30001
  type: NodePort